# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-64
@EXPLICIT
https://repo.continuum.io/pkgs/main/osx-64/blas-1.0-mkl.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/ca-certificates-2019.1.23-0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/intel-openmp-2019.1-144.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/jpeg-9b-he5867d9_2.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/libcxxabi-4.0.1-hcfea43d_1.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/libgfortran-3.0.1-h93005f0_2.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/libiconv-1.15-hdd342a3_7.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/libsodium-1.0.16-h3efe00b_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pandoc-2.2.3.2-0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/xz-5.2.4-h1de35cc_4.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/zlib-1.2.11-h1de35cc_3.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/libcxx-4.0.1-hcfea43d_1.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/libpng-1.6.36-ha441bb4_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/mkl-2018.0.3-1.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/openssl-1.1.1b-h1de35cc_1.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/tk-8.6.8-ha441bb4_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/expat-2.2.6-h0a44026_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/icu-58.2-h4b95b61_1.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/libffi-3.2.1-h475c297_4.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/ncurses-6.1-h0a44026_1.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/pcre-8.42-h378b8a2_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/zeromq-4.3.1-h0a44026_3.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/gettext-0.19.8.1-h15daf44_3.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/libedit-3.1.20181209-hb402a30_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/libxml2-2.9.9-hab757c2_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/readline-7.0-h1de35cc_5.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/glib-2.56.2-hd9629dc_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/libxslt-1.1.33-h33a18ac_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/sqlite-3.26.0-ha441bb4_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/dbus-1.13.6-h90a0687_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/python-3.7.2-haf84260_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/qt-5.9.7-h468cd18_1.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/alabaster-0.7.12-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/anaconda-custom-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/appnope-0.1.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/asn1crypto-0.24.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/backcall-0.1.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/certifi-2018.11.29-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/chardet-3.0.4-py37_1.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/cloudpickle-0.8.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/cymem-2.0.2-py37h04f5b5a_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/decorator-4.3.2-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/dill-0.2.8.2-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/docutils-0.14-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/entrypoints-0.3-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/idna-2.8-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/imagesize-1.1.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/ipython_genutils-0.2.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/lazy-object-proxy-1.3.1-py37h1de35cc_2.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/lxml-4.3.1-py37hef8c89e_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/markupsafe-1.1.1-py37h1de35cc_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/mccabe-0.6.1-py37_1.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/mistune-0.8.4-py37h1de35cc_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/msgpack-python-0.6.1-py37h04f5b5a_1.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/murmurhash-1.0.1-py37h0a44026_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/numpy-base-1.15.4-py37h8a80b8c_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pandocfilters-1.4.2-py37_1.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/parso-0.3.4-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pickleshare-0.7.5-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/plac-0.9.6-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/psutil-5.5.0-py37h1de35cc_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/ptyprocess-0.6.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pycodestyle-2.5.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pycparser-2.19-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pyflakes-2.1.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pyparsing-2.3.1-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pysocks-1.6.8-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/python.app-2-py37_9.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pytz-2018.9-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pyzmq-18.0.0-py37h0a44026_0.tar.bz2
https://repo.continuum.io/pkgs/main/noarch/qtpy-1.6.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/regex-2018.11.22-py37h1de35cc_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/rope-0.12.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/sip-4.19.8-py37h0a44026_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/six-1.12.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/snowballstemmer-1.2.1-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/sphinxcontrib-1.0-py37_1.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/testpath-0.4.2-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/toolz-0.9.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/tornado-5.1.1-py37h1de35cc_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/tqdm-4.31.1-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/ujson-1.35-py37h1de35cc_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/wcwidth-0.1.7-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/webencodings-0.5.1-py37_1.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/wrapt-1.10.11-py37h1de35cc_2.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/wurlitzer-1.0.2-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/astroid-2.1.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/babel-2.6.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/cffi-1.12.1-py37hb5b8e2f_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/cytoolz-0.9.0.1-py37h1de35cc_1.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/jedi-0.13.3-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/keyring-18.0.0-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/neotime-1.7.4-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/packaging-19.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pexpect-4.6.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/preshed-2.0.1-py37h0a44026_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pyqt-5.9.2-py37h655552a_2.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/python-dateutil-2.8.0-py37_0.tar.bz2
https://repo.continuum.io/pkgs/main/noarch/qtawesome-0.5.6-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/setuptools-40.8.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/sphinxcontrib-websupport-1.1.0-py37_1.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/traitlets-4.3.2-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/bleach-3.1.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/cryptography-2.5-py37ha12b0ac_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/isort-4.3.8-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/jinja2-2.10-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/jsonschema-2.6.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/jupyter_core-4.4.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pygments-2.3.1-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/wheel-0.33.1-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/jupyter_client-5.2.4-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/nbformat-4.4.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pip-19.0.3-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/prompt_toolkit-2.0.9-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pylint-2.2.2-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pyopenssl-19.0.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/ipython-7.2.0-py37h39e3cac_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/nbconvert-5.3.1-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/urllib3-1.24.1-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/ipykernel-5.1.0-py37h39e3cac_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/requests-2.21.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/qtconsole-4.4.3-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/sphinx-1.8.4-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/spyder-kernels-0.4.2-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/numpydoc-0.8.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/spyder-3.3.3-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/mkl_fft-1.0.6-py37hb8a8100_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/mkl_random-1.0.1-py37h5d10147_1.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/numpy-1.15.4-py37h6a91979_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/msgpack-numpy-0.4.3.2-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pandas-0.24.1-py37h0a44026_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/thinc-6.12.1-py37h4f467ca_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/spacy-2.0.16-py37h6440ff4_0.tar.bz2
